replicaCount: 1

image:
  repository: lian1280/ceramicraft-order-mservice
  tag: v0.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  grpcPort: 5001

livenessProbe:
  path: /order-ms/v1/ping
  initialDelaySeconds: 10
  periodSeconds: 5
readinessProbe:
  path: /order-ms/v1/ping
  initialDelaySeconds: 10
  periodSeconds: 5

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

volumes:
  configMapName: order-ms-config
  logPath: /tmp/logs/order-ms
