apiVersion: v1
kind: ConfigMap
metadata:
  name: comment-ms-config
data:
  config.yml: |
    grpc:
      host: "0.0.0.0"
      port: 5001
      connect_timeout: 3
      max_pool_size: 200

    http:
      host: "0.0.0.0"
      port: 8080

    log:
      level: debug
      file_path: ./logs/ceramicraft-comment-mservice.log

    mysql:
      host: "172.31.2.221"
      port: "3306"
      userName: "root"
      dbName: "comment_db"

    mongo:
      host: "172.31.2.221"
      port: "27017"
      database: "comment_db"

    redis:
      host: "172.31.2.221"
      port: "6379"