apiVersion: v1
kind: ConfigMap
metadata:
  name: order-ms-config
data:
  config.yml: |
    grpc:
      host: "0.0.0.0"
      port: 5001
      connect_timeout: 3
      max_pool_size: 200

    http:
      host: "0.0.0.0"
      port: 8080

    log:
      level: debug
      file_path: ./logs/ceramicraft-order-mservice.log

    mysql:
      host: "172.31.2.221"
      port: "3306"
      userName: "root"
      dbName: "order_db"

    commodityClient:
      host: "product-ms-svc.default.svc.cluster.local"
      port: 5001

    paymentClient:
      host: "payment-ms-svc.default.svc.cluster.local"
      port: 5001

    kafka:
      host: "172.31.2.221"
      port: 29092