apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: nginx-main
    files:
      - nginx.conf
  - name: nginx-sub
    files:
      - conf.d/locations.common
      - conf.d/default.conf
